# Generated by Django 4.2.7 on 2023-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_source_last_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
