# Generated by Django 4.2.7 on 2023-11-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_source_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='spider_class',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
