# Generated by Django 4.2.7 on 2023-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_source_spider_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('ST', 'static'), ('DM', 'dynamic')], default='ST', max_length=2),
        ),
    ]
