# Generated by Django 4.2.7 on 2023-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='max_pages_per_session',
            field=models.IntegerField(default=10),
        ),
    ]
