# Generated by Django 4.2.7 on 2023-11-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_source_max_pages_per_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
